package com.woniu.pojo;
// Generated 2020-2-18 12:52:25 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
@SuppressWarnings("serial")
public class Role implements java.io.Serializable {

	private int rid;
	private String rname;
	@SuppressWarnings("rawtypes")
	private Set users = new HashSet(0);

	public Role() {
	}

	public Role(int rid) {
		this.rid = rid;
	}

	@SuppressWarnings("rawtypes")
	public Role(int rid, String rname, Set users) {
		this.rid = rid;
		this.rname = rname;
		this.users = users;
	}

	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	@SuppressWarnings("rawtypes")
	public Set getUsers() {
		return this.users;
	}

	@SuppressWarnings("rawtypes")
	public void setUsers(Set users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "Role [rid=" + rid + ", rname=" + rname +  "]";
	}

}
