package com.woniu.pojo;
// Generated 2020-2-18 12:52:25 by Hibernate Tools 5.4.7.Final

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {

	private int uid;
	private Role role;
	private String uname;
	private String upwd;

	public User() {
	}

	public User(int uid) {
		this.uid = uid;
	}

	public User(int uid, Role role, String uname, String upwd) {
		this.uid = uid;
		this.role = role;
		this.uname = uname;
		this.upwd = upwd;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

}
